//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcwProject.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int CustomerOrderId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public double Amount { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Barcode { get; set; }
        public string Guid { get; set; }
    
        public virtual CustomerOrderHeader CustomerOrderHeader { get; set; }
        public virtual Product Product { get; set; }
    }
}
