//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcwProject.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrderHeader()
        {
            this.CustomerOrder = new HashSet<CustomerOrder>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public string OrderAdress { get; set; }
        public double OrderPrice { get; set; }
        public System.DateTime Date_ { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrder { get; set; }
    }
}
